# Generated by Django 6.0.3 on 2026-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksample',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
