// Shared demo/seed data used by browse, gigs, and public portfolio pages
// when the backend is unreachable or returns empty results.

export const SEED_PROFILES = [
  {
    id: 9001,
    username: "amara_diallo",
    user_username: "amara_diallo",
    name: "Amara Diallo",
    discipline: "Beauty & Cosmetology",
    school: "University of Nairobi",
    location: "Nairobi, Kenya",
    bio: "Hair artist and makeup specialist focused on natural African styles and bridal looks. Available for events and editorial shoots.",
    skills: ["Hair Styling", "Bridal Makeup", "Natural Hair", "Nail Art"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9002,
    username: "kevin_ochieng",
    user_username: "kevin_ochieng",
    name: "Kevin Ochieng",
    discipline: "Web/App Development",
    school: "Strathmore University",
    location: "Nairobi, Kenya",
    bio: "Full-stack developer building clean, fast web apps. Passionate about fintech and e-commerce solutions for African markets.",
    skills: ["React", "Node.js", "Django", "PostgreSQL", "UI Design"],
    open_to_work: true,
    is_premium: true,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9003,
    username: "fatima_alhassan",
    user_username: "fatima_alhassan",
    name: "Fatima Al-Hassan",
    discipline: "Graphic Design",
    school: "USIU Africa",
    location: "Nairobi, Kenya",
    bio: "Brand identity designer specialising in vibrant, culturally-rooted visual systems for African businesses and startups.",
    skills: ["Brand Identity", "Illustrator", "Figma", "Motion Graphics"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9004,
    username: "daniel_kamau",
    user_username: "daniel_kamau",
    name: "Daniel Kamau",
    discipline: "Fashion & Styling",
    school: "Kenya Institute of Fashion Design",
    location: "Nairobi, Kenya",
    bio: "Fashion designer and personal stylist with a focus on sustainable, locally-sourced fabrics and Afro-contemporary aesthetics.",
    skills: ["Fashion Design", "Personal Styling", "Textile Sourcing", "Lookbook"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9005,
    username: "aisha_mwangi",
    user_username: "aisha_mwangi",
    name: "Aisha Mwangi",
    discipline: "Beauty & Cosmetology",
    school: "Kenyatta University",
    location: "Thika, Kenya",
    bio: "Certified cosmetologist specialising in protective styles, locs, and advanced skincare treatments.",
    skills: ["Protective Styles", "Locs", "Skincare", "Wigs", "Colour"],
    open_to_work: false,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9006,
    username: "brian_otieno",
    user_username: "brian_otieno",
    name: "Brian Otieno",
    discipline: "Web/App Development",
    school: "Jomo Kenyatta University",
    location: "Nairobi, Kenya",
    bio: "Mobile-first developer. I build Android and cross-platform apps that solve everyday problems for East African consumers.",
    skills: ["Flutter", "Kotlin", "Firebase", "REST APIs", "UX Design"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9007,
    username: "zara_njeri",
    user_username: "zara_njeri",
    name: "Zara Njeri",
    discipline: "Graphic Design",
    school: "Daystar University",
    location: "Nairobi, Kenya",
    bio: "Illustrator and social-media designer. I help small businesses build a consistent, scroll-stopping visual presence.",
    skills: ["Illustration", "Canva Pro", "Photoshop", "Social Media Graphics"],
    open_to_work: true,
    is_premium: true,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9008,
    username: "marcus_wafula",
    user_username: "marcus_wafula",
    name: "Marcus Wafula",
    discipline: "Fashion & Styling",
    school: "Technical University of Mombasa",
    location: "Mombasa, Kenya",
    bio: "Wardrobe stylist and fashion photographer. I create editorial looks that blend coastal Swahili culture with modern streetwear.",
    skills: ["Wardrobe Styling", "Editorial Shoots", "Streetwear", "Fashion Photography"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9009,
    username: "priya_sharma",
    user_username: "priya_sharma",
    name: "Priya Sharma",
    discipline: "Web/App Development",
    school: "Aga Khan University",
    location: "Nairobi, Kenya",
    bio: "UI/UX designer and front-end developer. I craft user-centric interfaces that are both beautiful and accessible.",
    skills: ["Figma", "React", "Tailwind CSS", "User Research", "Prototyping"],
    open_to_work: true,
    is_premium: false,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
  {
    id: 9010,
    username: "naledi_dube",
    user_username: "naledi_dube",
    name: "Naledi Dube",
    discipline: "Graphic Design",
    school: "Nairobi Design Institute",
    location: "Nairobi, Kenya",
    bio: "Typographer and print designer specialising in packaging, event branding, and publication layouts.",
    skills: ["Typography", "InDesign", "Packaging Design", "Print", "Branding"],
    open_to_work: false,
    is_premium: true,
    avatar_url: null,
    cover_image_url: null,
    social_links: {},
  },
];

// Demo work samples keyed by discipline — shown on portfolio pages when backend is down
export const SEED_WORK_SAMPLES: Record<string, Array<{ id: number; title: string; description: string; sample_type: string; link: string; tags: string[] }>> = {
  "Beauty & Cosmetology": [
    { id: 1, title: "Bridal Natural Hair Look", description: "Full day bridal package — hair, makeup, and nails for a garden wedding in Karen.", sample_type: "link", link: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=400&fit=crop", tags: ["Bridal", "Natural Hair", "Makeup"] },
    { id: 2, title: "Editorial Afro Shoot", description: "Creative editorial shoot for Nairobi Fashion Week backstage.", sample_type: "link", link: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=400&fit=crop", tags: ["Editorial", "Afro", "Events"] },
    { id: 3, title: "Skin Prep & Glam", description: "Full glam transformation for a corporate headshot session.", sample_type: "link", link: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=400&fit=crop", tags: ["Glam", "Skincare", "Corporate"] },
  ],
  "Web/App Development": [
    { id: 4, title: "E-Commerce Dashboard", description: "Full-stack inventory and sales dashboard built with Next.js and Django REST for a Nairobi retailer.", sample_type: "link", link: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop", tags: ["Next.js", "Django", "Dashboard"] },
    { id: 5, title: "Mobile Payments App", description: "Flutter app integrating M-Pesa STK push for peer-to-peer payments.", sample_type: "link", link: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=400&fit=crop", tags: ["Flutter", "M-Pesa", "Mobile"] },
    { id: 6, title: "Restaurant Booking Site", description: "Responsive website with online menu, real-time table booking, and admin panel.", sample_type: "link", link: "https://images.unsplash.com/photo-1555421689-d68471e189f2?w=600&h=400&fit=crop", tags: ["React", "Booking", "UI/UX"] },
  ],
  "Graphic Design": [
    { id: 7, title: "Jua Coffee Co. Branding", description: "Complete brand identity for a specialty coffee shop — logo, colour system, and packaging.", sample_type: "link", link: "https://images.unsplash.com/photo-1600275669439-14e40452d20b?w=600&h=400&fit=crop", tags: ["Branding", "Logo", "Packaging"] },
    { id: 8, title: "Social Media Campaign", description: "12-piece Instagram grid campaign for a fashion brand launch.", sample_type: "link", link: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&h=400&fit=crop", tags: ["Social Media", "Campaign", "Illustration"] },
    { id: 9, title: "Event Poster Series", description: "A series of 3 event posters for a Nairobi music festival using bold Afrocentric typography.", sample_type: "link", link: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=600&h=400&fit=crop", tags: ["Print", "Typography", "Events"] },
  ],
  "Fashion & Styling": [
    { id: 10, title: "Afro-Futurist Editorial", description: "Styled a 6-look editorial shoot blending traditional Kenyan fabrics with modern silhouettes.", sample_type: "link", link: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop", tags: ["Editorial", "Styling", "Afrocentric"] },
    { id: 11, title: "Street Style Campaign", description: "Personal styling for a CBD street-style campaign — 4 models, 3 looks each.", sample_type: "link", link: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&h=400&fit=crop", tags: ["Street Style", "Campaign", "Urban"] },
    { id: 12, title: "Sustainable Capsule Collection", description: "Designed a 10-piece capsule using upcycled kitenge fabrics sourced from Gikomba Market.", sample_type: "link", link: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&h=400&fit=crop", tags: ["Fashion Design", "Sustainable", "Capsule"] },
  ],
};

export const SEED_GIGS = [
  {
    id: 8001,
    title: "Logo Design for Nairobi Tech Startup",
    discipline: "Graphic Design",
    status: "open",
    description: "We need a modern, clean logo for our fintech startup. Must convey trust and innovation. Deliverables: primary logo, icon, color palette, and brand guide.",
    budget: "KES 8,000 – 15,000",
    deadline: "2026-05-15T00:00:00Z",
    client_name: "TechBridge Kenya",
    client_profile: 0,
  },
  {
    id: 8002,
    title: "Website Redesign for Nairobi Restaurant",
    discipline: "Web/App Development",
    status: "open",
    description: "Our restaurant website is outdated. We need a new responsive site with an online menu, booking form, and gallery. Mobile-first design is a must.",
    budget: "KES 20,000 – 35,000",
    deadline: "2026-05-20T00:00:00Z",
    client_name: "Nyama Choma House",
    client_profile: 0,
  },
  {
    id: 8003,
    title: "Campaign Styling for Fashion Lookbook",
    discipline: "Fashion & Styling",
    status: "open",
    description: "Seeking a creative stylist for a 1-day editorial fashion shoot. We will supply 6 outfits and a photographer. Need someone who can style models and arrange creative compositions.",
    budget: "KES 12,000",
    deadline: "2026-05-10T00:00:00Z",
    client_name: "Vivid Collective",
    client_profile: 0,
  },
  {
    id: 8004,
    title: "Bridal Makeup & Hair for Wedding Event",
    discipline: "Beauty & Cosmetology",
    status: "open",
    description: "Looking for an experienced MUA and hair stylist for a wedding on May 25th. Party of 4: bride + 3 bridesmaids. Must have a portfolio of previous bridal work.",
    budget: "KES 18,000 – 25,000",
    deadline: "2026-05-25T00:00:00Z",
    client_name: "Private Client",
    client_profile: 0,
  },
  {
    id: 8005,
    title: "Brand Identity Package for Coffee Shop",
    discipline: "Graphic Design",
    status: "open",
    description: "New specialty coffee shop opening in Westlands needs full brand identity: logo, colour palette, typography, packaging stickers, and social media templates.",
    budget: "KES 25,000 – 40,000",
    deadline: "2026-06-01T00:00:00Z",
    client_name: "Jua Coffee Co.",
    client_profile: 0,
  },
  {
    id: 8006,
    title: "Mobile App UI for Delivery Service",
    discipline: "Web/App Development",
    status: "open",
    description: "We are building a last-mile delivery app for Nairobi. Need a UI/UX designer to create polished Figma screens for the rider and customer apps. 20 screens total.",
    budget: "KES 30,000 – 50,000",
    deadline: "2026-06-10T00:00:00Z",
    client_name: "RushRoute Ltd.",
    client_profile: 0,
  },
  {
    id: 8007,
    title: "Hair Styling for Fashion Show",
    discipline: "Beauty & Cosmetology",
    status: "open",
    description: "Annual student fashion show needs 2 hair stylists for backstage. You will work with 12 models over 3 hours. Theme is Afro-Futurist.",
    budget: "KES 8,000 per stylist",
    deadline: "2026-05-28T00:00:00Z",
    client_name: "KIFD Events Team",
    client_profile: 0,
  },
  {
    id: 8008,
    title: "Social Media Graphics for 3 Months",
    discipline: "Graphic Design",
    status: "open",
    description: "Looking for a graphic designer to create 12 social media posts per month (Instagram + Facebook). Posts should follow our brand guide. Monthly retainer.",
    budget: "KES 10,000/month",
    deadline: "2026-06-15T00:00:00Z",
    client_name: "Savana Health Products",
    client_profile: 0,
  },
];
